# Generated by Django 2.1b1 on 2019-03-02 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clueless', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clueless.Games'),
        ),
        migrations.AddField(
            model_name='cards',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clueless.Players'),
        ),
        migrations.AddField(
            model_name='cards',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locations',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clueless.Games'),
        ),
        migrations.AddField(
            model_name='locations',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='players',
            name='client_ip',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='players',
            name='client_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='players',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clueless.Games'),
        ),
        migrations.AddField(
            model_name='players',
            name='game_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='players',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clueless.Locations'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='games',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
