# Generated by Django 2.1b1 on 2019-03-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clueless', '0002_auto_20190302_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='their_turn',
            field=models.BooleanField(default=False),
        ),
    ]
