# Generated by Django 2.1b1 on 2019-03-03 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Clueless', '0003_players_their_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
