# Generated by Django 2.1b1 on 2019-03-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clueless', '0004_games_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='solution',
            field=models.BooleanField(default=False),
        ),
    ]
