# Generated by Django 2.1b1 on 2019-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clueless', '0006_players_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='turn_order',
            field=models.CharField(default='', max_length=200),
        ),
    ]
