# Generated by Django 2.1b1 on 2019-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clueless', '0007_games_turn_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='suggested',
            field=models.BooleanField(default=False),
        ),
    ]
