# Generated by Django 2.1b1 on 2019-03-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clueless', '0008_cards_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='client_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
